
all:
	gcc HelloServer4_MPTCP.c -o HelloServer4_MPTCP
	gcc HelloClient_MPTCP.c -o HelloClient_MPTCP

client:
	gcc HelloClient_MPTCP.c -o HelloClient_MPTCP
	
server:
	gcc HelloServer4_MPTCP.c -o HelloServer4_MPTCP
	
#.PHONEY clea
clean:
	rm HelloClient_MPTCP
	rm HelloServer4_MPTCP
